## Refer to http://caffe.berkeleyvision.org/installation.html

# The following variables are set via gibraltar's Makefile:
# CUDA_ARCH := -gencode arch=compute_30,code=sm_30

# Use CUDA and cuDNN.
CPU_ONLY := 0
CUDA_DIR := /usr/local/cuda
USE_CUDNN := 1

# use g++ for compilation.
CUSTOM_CXX := g++

# build directories
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Enable pretty builds.
Q ?= @

# Use Atlas by default.
BLAS ?= atlas

# We need to be able to find Python.h and numpy/arrayobject.h.
WITH_PYTHON_LAYER := 1
PYTHON_INCLUDE := /usr/include/python2.7 \
  /usr/local/lib/python2.7/dist-packages/numpy/core/include/ \
  /usr/lib/python2.7/dist-packages/numpy/core/include
PYTHON_LIB := /usr/lib

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

# Don't test.
TEST_GPU := 0
